import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir } from 'node:fs/promises';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outputDirectory = 'dist';
const releaseFiles = ['manifest.json', 'styles.css'];

const copyReleaseFilesPlugin = {
	name: 'copy-release-files',
	setup(build) {
		build.onStart(async () => {
			await mkdir(outputDirectory, { recursive: true });
			await Promise.all(releaseFiles.map((file) =>
				copyFile(file, `${outputDirectory}/${file}`),
			));
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${outputDirectory}/main.js`,
	minify: prod,
	plugins: [copyReleaseFilesPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
